### ISSUE TITLE
responsive bug

### ISSUE THREAD

**Issue by benjithorpe** [DavidMatthewFraser/easy-to-git#35]
the search bar is too huge for mobile size

![Screenshot (6)](https://user-images.githubusercontent.com/61359802/89701288-ddb68d80-d924-11ea-9368-5ed962e7a25a.png)

**Comment by DavidMatthewFraser** [comment]
I agree.

The search bar (as well and most of the page elements) would benefit from bootstrap grid - concerning mobile responsiveness. We could use a media query ... but we are already using Bootstrap for the 'carousel' and button styles. 

What are your thoughts?

**Comment by benjithorpe** [comment]
we could just use bootstrap for things we know will cause bugs, and use normal css for basic things we want to change.

**Comment by DavidMatthewFraser** [comment]
I added some Bootstrap so that the website is more mobile friendly. 

<img width="416" alt="Screen Shot 2020-08-08 at 4 13 19 PM" src="https://user-images.githubusercontent.com/47202564/89720684-16d91700-d992-11ea-9bc9-264dd9204f16.png">

However it looks worse on larger screens 

<img width="1282" alt="Screen Shot 2020-08-08 at 4 16 33 PM" src="https://user-images.githubusercontent.com/47202564/89720723-936bf580-d992-11ea-9737-cea79efaff66.png">

We'll have to work on it but this should work for now. Feel free to change any of this or request any changes to the design. Thanks for brining up this bug.
